# Numpy




In [ ]:
  #list : 여러타입의 값을 저장하는 자료구조 , 속도느리다. 
#ndarray :하나의 타입만 가능 ,  n차원의 배열 , 속도빠르다.
#       자동형변환 

In [ ]:
#pip install numpy
import numpy as np


In [ ]:
a = [1,2,3,4,5,"리스트"]
b = np.array([1,2,3,4,5,"배열"])
print(a)
print(b)

[1, 2, 3, 4, 5, '리스트']
['1' '2' '3' '4' '5' '배열']


In [ ]:
a = [1,2,3,4,5]
a *2
a + a

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
b = np.array([1,2,3,4,5])
b+10
b*10

array([10, 20, 30, 40, 50])

In [ ]:

a = list(range(10000))
b = list(range(10000))


In [ ]:
%timeit a+b    #58.6 µs  -> 56600 ns

The slowest run took 4.30 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 58.6 µs per loop


In [ ]:
a = np.array(range(10))
b = np.array(range(10))


In [ ]:
%timeit a+b   #520 ns

The slowest run took 41.08 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 520 ns per loop


In [ ]:
a = np.array([1,2,3,4,5]) #, dtype="string_")
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
s = np.array(["A","B","C"], dtype="string_")
a.shape
a2.shape
a3.shape

(2, 2, 3)

In [ ]:
type(a)
a.dtype  #a의 data type
s.dtype
a.dtype  #a의 data type

dtype('int64')

In [ ]:
a = np.array([1,2,3,4,5])
a.shape
alist = [10,20,30,40]
blist = [11,12,13,14]

b = np.array([alist, blist])
b.shape

alist = [[10,20,30,40],[10,20,30,40]]
blist = [[11,12,13,14],[11,12,13,14]]

c = np.array([alist, blist, blist])
c.shape



(3, 2, 4)

In [ ]:
a = np.array([1,2,3,4,5], dtype="float64")
a.dtype

dtype('float64')

In [ ]:
np.zeros(shape=10)
np.zeros(shape=10, dtype="float64")
np.zeros(shape=(2,3), dtype="float64")
np.zeros(shape=(4,2,3))

np.ones(shape=10)
np.ones(shape=(4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.full(shape=10, fill_value=5)
np.full(shape=(3,4), fill_value=5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
np.array(list(range(10))) + 100
np.ones(shape=10) + 100
np.zeros(shape=(2,3)) + 100
np.full(shape=(2,4), fill_value=5) + 100

array([[105, 105, 105, 105],
       [105, 105, 105, 105]])

In [ ]:
np.arange(0,101, 10, dtype="float64")

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.linspace(1,10,endpoint=True, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#0~1사이의 실수값 (무작위)
np.random.random()
np.random.seed(100)
np.random.random(size=(3,4))



array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212]])

In [ ]:
np.random.randint(1,45)

32

In [ ]:
np.random.random() * 100

95.0184314039969

In [ ]:
np.random.choice(45, size=6, replace=False)

array([25,  1, 24,  5, 42, 11])

In [ ]:
a = np.array([10,8,40,77,99])

a[1]

a = np.array([[10,8,40,77,99],[11,22,33,44,55]])
print("차원:", a.ndim)
print("모양:", a.shape)
print("요소갯수:", a.size)
print("data type:", a.dtype)
print("요소접근:", a[1,0])

차원: 2
모양: (2, 5)
요소갯수: 10
data type: int64
요소접근: 11




---



In [ ]:
a = np.array([10,8,40,77,99])
a[:]
a[::2]
a[::-1]
a[2:]

array([40, 77, 99])

In [ ]:
a = np.array([[10,8,40,77,99],[11,22,33,44,55]])

#a[행, 열]
a[0][2]
a[0,2]

arr2 = a[:1, ]  #[[10,8,40,77,99]]
arr1 = a[0]   #[10,8,40,77,99] 
print(arr1.shape, arr1.ndim,"차원", arr1.size)
print(arr2.shape, arr2.ndim, "차원", arr2.size)

#행의 특정 요소(칼럼)만 추출 
a[:, [0,2]]

(5,) 1 차원 5
(1, 5) 2 차원 5


array([[10, 40],
       [11, 33]])

In [ ]:
x = np.zeros(shape=(3,6))
y = x[:3, ::2]  #oracle에서 view비슷 

#y가 x의 일부를 보고있다. y를 통해서 수정했다. 
y[:, 2] = 99

x

array([[ 0.,  0.,  0.,  0., 99.,  0.],
       [ 0.,  0.,  0.,  0., 99.,  0.],
       [ 0.,  0.,  0.,  0., 99.,  0.]])

In [ ]:
#복사했기때문에 원본은 변경되지않음 
z = x.copy()[:3, ::2]
z[:, 1] = 88
x

array([[ 0.,  0.,  0.,  0., 99.,  0.],
       [ 0.,  0.,  0.,  0., 99.,  0.],
       [ 0.,  0.,  0.,  0., 99.,  0.]])

In [ ]:
#1 <= <6 1차원배열 
a = np.arange(1,6)
print(a.shape)

y = a[:, np.newaxis]
print(y.shape)

z = y[:, np.newaxis]
print(z.shape)


y2 = a[ np.newaxis, :]
print(y2.shape)

z2 = y2[ np.newaxis,:]
print(z2.shape)

z2

(5,)
(5, 1)
(5, 1, 1)
(1, 5)
(1, 1, 5)


array([[[1, 2, 3, 4, 5]]])

In [ ]:
x = np.array([1,2,3,4,5])
x = np.arange(1,6)

b = [True,False,True,False, True]

x[b]
x[[True,False,True,False, True]]

x > 3
x [ [False, False, False,  True,  True] ]
x [ x > 3 ]

np.where( x > 3 ,"3이상","3이하")

array(['3이하', '3이하', '3이하', '3이상', '3이상'], dtype='<U3')

In [ ]:
arr = np.arange(20)


#재구조화 ..View이다. 복사아님 
arr2 = np.reshape(arr, (4,5))
arr3 = np.reshape(arr, (2,10))

arr[0] = 99  #원본수정 
arr3[0,4] = 88
arr2

array([[99,  1,  2,  3, 88],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr1 = np.arange(1,6)
arr2 = np.arange(10,15)

#벡터연산  
arr1 + arr2

#합치기 
##list합치기 
[1,2,3,4,5] + [10,11,12,13,14]

np.concatenate((arr1, arr2))



array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [ ]:
arr1 = np.reshape(np.arange(1,11),(2,5))
arr2 = np.reshape(np.arange(10,20),(2,5))

arr1
arr2
np.concatenate((arr1, arr2))#axis=0 생략됨 ,행방향 
arr3 = np.concatenate((arr1, arr2), axis=0)
arr4 = np.concatenate((arr1, arr2), axis=1)

print(arr3.shape)
print(arr4.shape)

(4, 5)
(2, 10)


In [ ]:
arr3 = np.vstack((arr1, arr2))  #axis=0와 같다.
arr4 = np.hstack((arr1, arr2))#axis=1와 같다.

In [ ]:
np.split(arr3, [2]) #axis=0와 같다. 행방향나누기 
np.split(arr3, [2], axis=0) 
np.split(arr3, [2], axis=1) #열방향나누기 

[array([[ 1,  2],
        [ 6,  7],
        [10, 11],
        [15, 16]]), array([[ 3,  4,  5],
        [ 8,  9, 10],
        [12, 13, 14],
        [17, 18, 19]])]

In [ ]:
arr = np.arange(1,11)
np.add.reduce(arr) #모두 합계
np.add.accumulate(arr) #과정이 모두return 

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
np.sum(arr)
np.mean(arr)
arr = np.array([99,55,66,22,100,55,88,33])

#max값의 위치(index)
np.argmax(arr)

#max값 
arr[ np.argmax(arr) ]

100

In [ ]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.arange(10,160,10).reshape(3,5)
d = np.hstack([a,b])
e = np.vstack((d,c))
np.vstack((e,e))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [ ]:
a = np.ones((2,3,4))
b = np.arange(4)  
#[[[0,1,2,3],[0,1,2,3],[0,1,2,3]] ,
# [[0,1,2,3],[0,1,2,3],[0,1,2,3]] ] 

print(a.shape, b.shape)

a + b


(2, 3, 4) (4,)


array([[[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]],

       [[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]]])

# 판다스

In [ ]:
#!pip install pandas

In [ ]:
import pandas as pd

#Series -->1차원
#DataFrame -->2차원 

In [ ]:
a = pd.Series([10,20,30,40,50])
b = pd.Series(["사과","오렌지","귤","바나나","수박"])
type(a)

a.index
b.index
df = pd.DataFrame({"갯수":a, "이름":b})
df2 = pd.DataFrame([[10,20,30,40,50],["사과","오렌지","귤","바나나","수박"]])
df2

0    1   2    3   4
0  10   20  30   40  50
1  사과  오렌지   귤  바나나  수박

In [ ]:
s1 = pd.Series([10,20,30,40,50], index=["a","b","c","d","e"])
s2 = pd.Series(["사과","오렌지","귤","바나나","수박"],index=["a","b","c","d","e"])
df = pd.DataFrame({"갯수":s1, "이름":s2})
df

갯수   이름
a  10   사과
b  20  오렌지
c  30    귤
d  40  바나나
e  50   수박

In [ ]:
s1.index
s2[4]  #순서이용 
s2["e"]  #index이름 이용 
s2[[3,4]]

d    바나나
e     수박
dtype: object

In [ ]:
s1.head(2)

s1 = pd.Series([99,10,10,10,20,20,30])
s1.value_counts()
s1.size
s1.dtype  #문자인경우는 object
s1.sort_index()
s1.sort_values()

s1.unique()
s1.nunique()

s1.isin([10,20])

s1.max()

s1.idxmax()  #max값의 위치 

s1.describe()

count     7.000000
mean     28.428571
std      31.999256
min      10.000000
25%      10.000000
50%      20.000000
75%      25.000000
max      99.000000
dtype: float64

In [ ]:
s1 = pd.Series([np.NAN,np.nan,np.NaN, None,40,50])
s1.isnull()

#inplace=True : 수정사항을 원본에 반영한다. 
s1.fillna(99, inplace=True)
s1

0    99.0
1    99.0
2    99.0
3    99.0
4    40.0
5    50.0
dtype: float64

In [ ]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

s1 + s2
s1 * s2

0     10
1     40
2     90
3    160
4    250
dtype: int64

In [ ]:
aa = s1>=3

s1[aa]

s1 = pd.Series([10,20,30,40,50])
#괄호주의!!!
s1[ (s1>=30) & (s1 >= 40)]


3    40
4    50
dtype: int64

# DataFrame

In [ ]:
#직접생성


df2 = pd.DataFrame({
                   "개수": [10,20,30,40,50],
                   "이름": ["사과","오렌지","귤","바나나","수박"]
                  })
df2


개수   이름
0  10   사과
1  20  오렌지
2  30    귤
3  40  바나나
4  50   수박

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
cd drive/MyDrive/

/content/drive/MyDrive


In [ ]:
os.getcwd()

'/content/drive/My Drive'

In [ ]:
df1 = pd.read_csv("data/friend_list.csv")

#header=0  : 몇번째 row까지 header인지 
df1 = pd.read_csv("data/friend_list.csv", header=0)
df1 = pd.read_csv("data/friend_list_no_head.csv", header=None)  
#header가 없음 생략하면 첫번째row가 header가된다.header=None를 설정하면 header없이 읽어온다. 
df1.columns=["A","B","C"]  #칼럼수정한다. 

df1 = pd.read_csv("data/friend_list_tab.txt", sep="\t")  #csv가 아닌 text파일이 탭으로 분리된 경우 
df1 = pd.read_csv("data/friend_list.csv", header=0, index_col="name")  #index칼럼지정 
df1 


age        job
name                 
John    20    student
Jenny   30  developer
Nate    30    teacher
Julia   40    dentist
Brian   45    manager
Chris   25     intern

In [ ]:
df_sales = pd.read_excel("data/02. sales-funnel.xlsx", header=0)

In [ ]:
#backup...파일저장
df_sales.to_csv("data/sales-funnel.csv")
df_sales.to_excel("data/sales-funnel.xls")

In [ ]:
os.getcwd()

'/content/drive/MyDrive'

In [ ]:
df_sales.head(2)
df_sales.tail(3)
df_sales.shape
df_sales.size  #17*8

df_sales.columns

#실패 #
#df_sales.get_dtype_counts() 

df_sales.select_dtypes(include="int")
df_sales.select_dtypes(include="object")
df_sales.select_dtypes(exclude="int")

#dir(df_sales)

#df_sales.info()
#df_sales.describe()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Account   17 non-null     int64 
 1   Name      17 non-null     object
 2   Rep       17 non-null     object
 3   Manager   17 non-null     object
 4   Product   17 non-null     object
 5   Quantity  17 non-null     int64 
 6   Price     17 non-null     int64 
 7   Status    17 non-null     object
dtypes: int64(3), object(5)
memory usage: 1.2+ KB


Account   Quantity          Price
count      17.000000  17.000000      17.000000
mean   462254.235294   1.764706   30705.882353
std    259093.442862   1.032558   28444.605609
min    141962.000000   1.000000    5000.000000
25%    218895.000000   1.000000    7000.000000
50%    412290.000000   2.000000   30000.000000
75%    714466.000000   2.000000   40000.000000
max    740150.000000   5.000000  100000.000000

In [ ]:
df_sales2 = df_sales.drop(["Name","Account"], axis=1)

df_sales

In [ ]:

df2 = pd.DataFrame({
                   "개수": [10,None,30,40,50],
                   "이름": ["사과","오렌지",np.NaN,"바나나","수박"]
                  })
df2

개수   이름
0  10.0   사과
1   NaN  오렌지
2  30.0  NaN
3  40.0  바나나
4  50.0   수박

In [ ]:
df2.dropna()

개수   이름
0  10.0   사과
3  40.0  바나나
4  50.0   수박

In [ ]:
df2

개수   이름
0  10.0   사과
1   NaN  오렌지
2  30.0  NaN
3  40.0  바나나
4  50.0   수박

In [ ]:
#df_sales.sort_index(ascending=False)
df_sales.sort_values("Account", ascending=False)

In [ ]:
df_sales.rename(columns={"Account":"계좌"}, inplace=True)
df_sales

In [ ]:
df_sales.columns

Index(['계좌', 'Name', 'Rep', 'Manager', 'Product', 'Quantity', 'Price',
       'Status'],
      dtype='object')

In [ ]:
#df2.dropna(inplace=True)
df2.set_index("이름", inplace=True)

df2

개수
이름       
사과   10.0
바나나  40.0
수박   50.0

In [ ]:
df2.reset_index(inplace=True)
df2

이름    개수
0   사과  10.0
1  바나나  40.0
2   수박  50.0

In [ ]:
#get_dtype_counts() Deprecated since version 0.25.0. deprecated
#dtypes.value_counts() 로 대체됨 
df_sales.dtypes.value_counts() 

object    5
int64     3
dtype: int64

In [ ]:
df_sales.columns
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   계좌        17 non-null     int64 
 1   Name      17 non-null     object
 2   Rep       17 non-null     object
 3   Manager   17 non-null     object
 4   Product   17 non-null     object
 5   Quantity  17 non-null     int64 
 6   Price     17 non-null     int64 
 7   Status    17 non-null     object
dtypes: int64(3), object(5)
memory usage: 1.2+ KB


In [ ]:
df_sales.columns

Index(['계좌', 'Name', 'Rep', 'Manager', 'Product', 'Quantity', 'Price',
       'Status'],
      dtype='object')

In [ ]:
col = ['계좌', 'Name', 'Rep', 'Manager' ]
df_sales.drop(col, axis=1)

In [ ]:
df2["가격"] = [1000,2000,3000]
df2["개수"] = [10,20,30]
df2

개수    가격
이름           
사과   10  1000
바나나  20  2000
수박   30  3000

In [ ]:
df2["개수"]

이름
사과     10
바나나    20
수박     30
Name: 개수, dtype: int64

In [ ]:
df_sales.columns

Index(['계좌', 'Name', 'Rep', 'Manager', 'Product', 'Quantity', 'Price',
       'Status'],
      dtype='object')

# DtaFrame 칼럼추출 

In [ ]:
type(df_sales["계좌"])

pandas.core.series.Series

In [ ]:
type(df_sales[['계좌', 'Name', 'Rep']])



pandas.core.frame.DataFrame

In [ ]:
df_sales.columns

Index(['계좌', 'Name', 'Rep', 'Manager', 'Product', 'Quantity', 'Price',
       'Status'],
      dtype='object')

In [ ]:
df_sales.filter(items=['Name', 'Rep'])
df_sales.filter(like='Name')
df_sales.filter(regex='\w')  #\d

# Daframe 행 추출 

In [ ]:
df2

개수    가격
이름           
사과   10  1000
바나나  20  2000
수박   30  3000

In [ ]:
#index이름으로 접근 
df2.loc["바나나"]
df2.loc[["바나나","수박"]]

#index의 순서로 접근 
df2.iloc[0]
df2.iloc[[0,2]]

개수    가격
이름          
사과  10  1000
수박  30  3000

In [ ]:
df_sales.index

#loc : 이름
df_sales.loc[0]
df_sales.loc[[0,2,5]]

#iloc : 순서 
df_sales.iloc[0]
df_sales.iloc[[0,2,5]]

In [ ]:
#이름 접근
df_sales.loc[1, "Product"]

#순서 접근 
df_sales.iloc[1, 4]

'Software'

In [ ]:
df_sales.Product
df_sales["Product"]

aa = df_sales.Product == "CPU"

aa = df_sales.Product == "CPU"
df_sales2 = df_sales[(df_sales.Product == "CPU") & (df_sales.Quantity >= 2)]

In [ ]:
df_sales2.loc[4, "계좌"]
df_sales2.iloc[0, 0]

#####차원인 경우 .... DataFrame은 2차원이다. 
#axis=0 행우선 
df_sales2.sort_index(axis=0, ascending=False)

#axis=1 열우선 
df_sales2.sort_index(axis=1, ascending=True)

Manager          Name   Price  ...            Rep    Status      계좌
4    Debra Henley  Kiehn-Spinka   65000  ...  Daniel Hilton       won  146832
5    Debra Henley     Kulas Inc   40000  ...  Daniel Hilton   pending  218895
9   Fred Anderson    Herman LLC   65000  ...    Cedric Moss       won  141962
14  Fred Anderson   Keeling LLC  100000  ...     Wendy Yule       won  688981
15  Fred Anderson     Koepp Ltd   65000  ...     Wendy Yule  declined  729833

[5 rows x 8 columns]

In [ ]:
df_sales2.sort_values("Price")
df_sales2.sort_values(["Price","Status"], ascending=False)

df_sales2.sort_values(["Price","Status"], ascending=[False,True])


계좌          Name            Rep  ... Quantity   Price    Status
14  688981   Keeling LLC     Wendy Yule  ...        5  100000       won
15  729833     Koepp Ltd     Wendy Yule  ...        2   65000  declined
4   146832  Kiehn-Spinka  Daniel Hilton  ...        2   65000       won
9   141962    Herman LLC    Cedric Moss  ...        2   65000       won
5   218895     Kulas Inc  Daniel Hilton  ...        2   40000   pending

[5 rows x 8 columns]

In [ ]:
df_sales.groupby("Product")["Price"].sum()

df_sales.groupby("Product")["Name"].count()


Product
CPU            9
Maintenance    4
Monitor        1
Software       3
Name: Name, dtype: int64

In [ ]:
df_sales.groupby("Product")["Price"].agg(["count","sum","mean","max","min"])

count     sum          mean     max    min
Product                                                
CPU              9  465000  51666.666667  100000  30000
Maintenance      4   22000   5500.000000    7000   5000
Monitor          1    5000   5000.000000    5000   5000
Software         3   30000  10000.000000   10000  10000

In [ ]:
df_sales.groupby("Product").agg({"Price":["count","sum","mean","max","min"],
                                 "Quantity":["sum","mean","max","min"]
                                 })

Price                                ... Quantity                  
            count     sum          mean     max  ...      sum      mean max min
Product                                          ...                           
CPU             9  465000  51666.666667  100000  ...       17  1.888889   5   1
Maintenance     4   22000   5500.000000    7000  ...        8  2.000000   3   1
Monitor         1    5000   5000.000000    5000  ...        2  2.000000   2   2
Software        3   30000  10000.000000   10000  ...        3  1.000000   1   1

[4 rows x 9 columns]

In [ ]:
df_friend1 = pd.read_csv("data/friend_list.csv")
df_friend2 = pd.read_csv("data/friends_backup.csv")


df_friend2.drop("Unnamed: 0", axis=1, inplace=True)

df_friend2["name"] = ["존","제니","네이트","쥴리아","브라이언","몰라"]
df_friend2

name  age        job
0     존   20    student
1    제니   30  developer
2   네이트   30    teacher
3   쥴리아   40    dentist
4  브라이언   45    manager
5    몰라   25     intern

In [ ]:
df = pd.concat([df_friend1, df_friend2],ignore_index=True )
#df.reset_index()
df

name  age        job
0    John   20    student
1   Jenny   30  developer
2    Nate   30    teacher
3   Julia   40    dentist
4   Brian   45    manager
5   Chris   25     intern
6       존   20    student
7      제니   30  developer
8     네이트   30    teacher
9     쥴리아   40    dentist
10   브라이언   45    manager
11     몰라   25     intern

In [ ]:
df_person = pd.read_csv("data/survey_person.csv")
#df_person의 ident와 survey_survey의 person과 join
df_survey = pd.read_csv("data/survey_survey.csv")

df_person.merge(df_survey, left_on="ident", right_on="person")

ident   personal   family  taken person quant  reading
0   dyer    William     Dyer    619   dyer   rad     9.82
1   dyer    William     Dyer    619   dyer   sal     0.13
2   dyer    William     Dyer    622   dyer   rad     7.80
3   dyer    William     Dyer    622   dyer   sal     0.09
4     pb      Frank  Pabodie    734     pb   rad     8.41
5     pb      Frank  Pabodie    734     pb  temp   -21.50
6     pb      Frank  Pabodie    735     pb   rad     7.22
7     pb      Frank  Pabodie    751     pb   rad     4.35
8     pb      Frank  Pabodie    751     pb  temp   -18.50
9   lake   Anderson     Lake    734   lake   sal     0.05
10  lake   Anderson     Lake    751   lake   sal     0.10
11  lake   Anderson     Lake    752   lake   rad     2.19
12  lake   Anderson     Lake    752   lake   sal     0.09
13  lake   Anderson     Lake    752   lake  temp   -16.00
14  lake   Anderson     Lake    837   lake   rad     1.46
15  lake   Anderson     Lake    837   lake   sal     0.21
16   roe  Valentina  Roerich    752    roe   sal    41.60
17   roe  Valentina  Roerich    837    roe   sal    22.50
18   roe  Valentina  Roerich    844    roe   rad    11.25

In [ ]:
오주한